export { VerticalHookScene } from "./VerticalHookScene";
export { VerticalOldWayScene } from "./VerticalOldWayScene";
export { VerticalShiftScene } from "./VerticalShiftScene";
export { VerticalBeforeAfterScene } from "./VerticalBeforeAfterScene";
export { VerticalNewWayScene } from "./VerticalNewWayScene";
export { VerticalWhatYouLearnScene } from "./VerticalWhatYouLearnScene";
export { VerticalTestimonialScene } from "./VerticalTestimonialScene";
export { VerticalShowcaseScene } from "./VerticalShowcaseScene";
export { VerticalCTAScene } from "./VerticalCTAScene";
